require 'ba.autocommands.yank'
require 'ba.autocommands.moveindent'
require 'ba.autocommands.spell-check'
require 'ba.autocommands.replace-text'
require 'ba.autocommands.local-keymaps'
require 'ba.autocommands.close-on-leave'
